---

substitutions:
  name: hydroponikk
  board: esp32dev

esphome:
  name: ${name}

esp32:
  board: ${board}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

logger:

sensor:
  - platform: ntc
    id: temperatur_vann
    name: Temperatur vann
    sensor: temperatur_vann_motstand
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
  # HUSK: GND - thermistor - Vout (GPIO36) - R1 - 3.3V
  - platform: resistance
    id: temperatur_vann_motstand
    name: Temperatur vann motstand
    sensor: temperatur_vann_adc
    configuration: DOWNSTREAM
    # HUSK: Tilpasse motstandsverdi
    resistor: 5.6kOhm
  - platform: adc
    id: temperatur_vann_adc
    # HUSK : Tilpasse pin
    pin: GPIO36
    update_interval: never

switch:
  - platform: gpio
    id: temperatur_vann_vcc
    # HUSK : Tilpasse pin
    pin: GPIO16

interval:
  - interval: 60s
    then:
      - switch.turn_on: temperatur_vann_vcc
      - component.update: temperatur_vann_adc
      - switch.turn_off: temperatur_vann_vcc
